# Generated by Django 6.0 on 2025-12-31 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['is_visible', 'is_featured', 'ranking_score'], name='prov_vis_feat_score_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['is_visible', 'province', 'city'], name='prov_vis_prov_city_idx'),
        ),
    ]
