# Generated by Django 6.0 on 2025-12-31 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_providerprofile_prov_vis_feat_score_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'ordering': ('-plan_tier', '-ranking_score', '-rating_avg', '-rating_count', 'nombre_fantasia'), 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='providerprofile',
            name='prov_vis_feat_score_idx',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='plan_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='plan_tier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['is_visible', 'plan_tier', 'ranking_score'], name='prov_vis_tier_score_idx'),
        ),
    ]
