# Generated by Django 6.0 on 2025-12-30 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BASE', 'Base'), ('FEATURED', 'Destacado')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='ARS', max_length=10)),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Mensual')], default='MONTHLY', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activa'), ('CANCELED', 'Cancelada'), ('EXPIRED', 'Vencida')], default='PENDING', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('gateway', models.CharField(choices=[('MANUAL', 'Manual'), ('MP', 'Mercado Pago'), ('MOBBEX', 'Mobbex')], default='MANUAL', max_length=20)),
                ('gateway_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='catalog.providerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
