# Generated by Django 6.0 on 2025-12-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gateway_checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
