# Generated by Django 6.0 on 2025-12-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_gateway_checkout_url_and_more'),
        ('catalog', '0002_providerprofile_prov_vis_feat_score_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider', 'plan', 'status'], name='sub_prov_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider', 'status', 'current_period_end'], name='sub_prov_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['gateway', 'gateway_subscription_id'], name='sub_gateway_subid_idx'),
        ),
    ]
