# Generated by Django 6.0 on 2025-12-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_sub_prov_plan_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='sub_prov_plan_status_idx',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='billing_period',
        ),
        migrations.AddField(
            model_name='plan',
            name='interval_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gateway',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('MP', 'Mercado Pago')], default='MANUAL', max_length=20),
        ),
    ]
