# Generated by Django 6.0 on 2025-12-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Publicada'), ('PENDING', 'Pendiente'), ('HIDDEN', 'Oculta')], default='PENDING', max_length=20),
        ),
    ]
