# Generated by Django 6.0 on 2025-12-31 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_providerprofile_prov_vis_feat_score_idx_and_more'),
        ('reviews', '0002_alter_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='rev_prov_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'created_at'], name='rev_status_created_idx'),
        ),
    ]
