# Generated by Django 6.0 on 2025-12-31 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_providerprofile_prov_vis_feat_score_idx_and_more'),
        ('reviews', '0003_review_rev_prov_status_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='uniq_review_per_provider_reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_org',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PUBLIC', 'Público')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('reviewer__isnull', False)), fields=('provider', 'reviewer'), name='uniq_review_per_provider_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('reviewer__isnull', True), models.Q(('reviewer_email', ''), _negated=True)), fields=('provider', 'reviewer_email'), name='uniq_review_per_provider_email'),
        ),
    ]
