# Generated by Django 6.0 on 2025-12-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('HEADER', 'Header'), ('FOOTER', 'Footer'), ('RIGHT_RAIL', 'Right rail')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('sponsor_name', models.CharField(blank=True, default='', max_length=120)),
                ('image_url', models.URLField(blank=True, default='')),
                ('link_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('placement', '-weight', '-updated_at'),
                'indexes': [models.Index(fields=['placement', 'active'], name='ad_place_active_idx'), models.Index(fields=['starts_at', 'ends_at'], name='ad_dates_idx')],
            },
        ),
    ]
