# Generated by Django 6.0 on 2025-12-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='placement',
            field=models.CharField(choices=[('HEADER', 'Header'), ('FOOTER', 'Footer'), ('LEFT_RAIL', 'Left rail'), ('RIGHT_RAIL', 'Right rail')], db_index=True, max_length=20),
        ),
    ]
