# Generated by Django 6.0 on 2025-12-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_adbanner_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='animation',
            field=models.CharField(choices=[('NONE', 'Sin animación'), ('MARQUEE', 'Texto en movimiento'), ('PULSE', 'Pulso suave'), ('FLOAT', 'Logo flotando')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='background_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=20),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='creative_type',
            field=models.CharField(choices=[('IMAGE', 'Imagen'), ('COMPOSED', 'Banner con texto (logo + copy)')], default='COMPOSED', max_length=20),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='cta_text',
            field=models.CharField(blank=True, default='Conocé más', max_length=40),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='font_family',
            field=models.CharField(blank=True, default='ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial', max_length=120),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ads/logos/'),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
