# Generated by Django 6.0 on 2025-12-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adbanner_animation_adbanner_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='animation',
            field=models.CharField(choices=[('NONE', 'Sin animación'), ('PULSE', 'Pulso suave'), ('FLOAT', 'Logo flotando')], default='NONE', max_length=20),
        ),
        migrations.CreateModel(
            name='AdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('HEADER', 'Header'), ('FOOTER', 'Footer'), ('LEFT_RAIL', 'Left rail'), ('RIGHT_RAIL', 'Right rail')], max_length=20)),
                ('sponsor_name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('link_url', models.URLField(blank=True, default='')),
                ('creative_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('COMPOSED', 'Banner con texto')], default='IMAGE', max_length=20)),
                ('animation', models.CharField(choices=[('NONE', 'Sin animación'), ('PULSE', 'Pulso suave'), ('FLOAT', 'Logo flotando')], default='NONE', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('subtitle', models.CharField(blank=True, default='', max_length=180)),
                ('cta_text', models.CharField(blank=True, default='Conocé más', max_length=40)),
                ('background_color', models.CharField(blank=True, default='#0f172a', max_length=20)),
                ('text_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('font_family', models.CharField(blank=True, default='', max_length=120)),
                ('font_size', models.PositiveSmallIntegerField(default=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ads/requests/logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/requests/images/')),
                ('duration_months', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['placement', 'status'], name='adreq_place_status_idx'), models.Index(fields=['created_at'], name='adreq_created_idx')],
            },
        ),
    ]
