# Generated by Django 6.0 on 2025-12-31 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_adbanner_animation_adrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrequest',
            name='created_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='ads.adbanner'),
        ),
    ]
